### PR TITLE
Add promotion tab with form link

### PR DESCRIPTION
**Pull request by bkimminich**
and short explanation of the current promotion process. Added also a call for feedback on the WIP maturity level proposal.

### CODE REVIEW

**Comment by kingthorin** [comment]
Should use markdown instead of html tags?

**Comment by bkimminich** [comment]
It's HTML to resize the images as needed. I'm not sure Markdown would work consistently in Jekyll and GitHub.

**Comment by kingthorin** [comment]
Fair enough!

**Review by kingthorin — APPROVED** [review]
Outside approval 🤷

**Comment by psiinon** [comment]
Whats the benefit of keeping the proposal in a gdoc as opposed to copying the text here?
If we keep it in the gdoc then any problem making it globally accessible?
I'd much rather more people had access to it rather than less ;)

**Comment by bkimminich** [comment]
> Whats the benefit of keeping the proposal in a gdoc as opposed to copying the text here?
> If we keep it in the gdoc then any problem making it globally accessible?
> I'd much rather more people had access to it rather than less ;)

I wouldn't mix as-is-process with proposed enhancements, that just get mixed up too easily. We could of course have the proposal in its own MD-file in the repo instead of keeping it in GDocs. Although for early review and co-editing I think GDocs is easier to use.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
