### PR TITLE
Introduce Production maturity level

### PR DESCRIPTION
**Pull request by bkimminich**

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by secureideas — APPROVED** [review]
Looks good to me.

**Review by stevespringett — APPROVED** [review]
LGTM

**Comment by bkimminich** [comment]
image

This image for production level is currently used on the main projects overview. IMHO the icon is hard to make out (skyscrapers? statistics?) and the color is way too close to Flagship. We should stick to the agrees purple ⚙️ symbol as introduced via this PR.

**Comment by hblankenship** [comment]
I agree with the change to the icon. I will update it when I can.

**Comment by bkimminich** [comment]
So we go with `fa-city` in purple as submitted via #11?

**Comment by hblankenship** [comment]
Ah, I used the cog. You tell me which you prefer. :)

**Comment by psiinon** [comment]
+1 for the purple city 😄

**Pull request merged**
