### PR TITLE
Use and promote usage of Fontawesome icons

### PR DESCRIPTION
**Pull request by bkimminich**
image

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by stevespringett** [comment]
Do we want to take into consideration "standard" projects such as CycloneDX or have these remain the exceptions?

I didn't know what icon to use for standard so used open book icon, even though the standard is delivered as JSON schema, XML schema, and Protobuf.

https://owasp.org/www-project-cyclonedx/

**Comment by bkimminich** [comment]
Oh, we should definitely consider extending the types of projects, but maybe not in the same PR. Also, how would Integration Project, Security Pins or others be called, as they're not a "Standard" but special or unique in other ways.

Maybe we just need a "Special" category to catch all of these including CycloneDX?

**Comment by fzipi** [comment]
Maybe is just me, but maybe creating specific CSS for these? I mean, instead of using
```
<i class="fas fa-egg fa-2x" style="color:#53AAE5"></i>
```
Create the css that allows us to just do:
```
<i class="owasp-incubating-2x"></i>
```
The class should add the color and references to font awesome. Maybe we can't because they need to be composed only 🤔

**Comment by bkimminich** [comment]
I'll just merge this one myself now, because it had a blessing from @psiinon and threre were no complaints. The approach @fzipi proposed would be preferrable, but I'm not a  CSS 🧙, so I leave that for someone more gifted in that area.

**Pull request merged**
